---
exclude:
  - '**/vendor/**/*'
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      # The following cops do not apply to ERB templates
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Max: 150 # From the default 120, views with their HTML tend to have longer lines and this is fine.
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
