version: '3.4'
services:
  web_app:
    build:
      args:
        USER_ID: 1000
      context: .
    depends_on:
      - redis
    environment:
      - RAILS_PORT=3000 # Do not forget to change ports below when changing this
      - REDIS_URL="redis://redis:6379/1" # Name (same as the service below) and port of the redis server (don't forget to change port in redis service if it changes...)
    ports:
      - '3000:3000' # Do not forget to change RAILS_PORT above when changing this
    volumes:
      - .:/web_app # Same as $WORKDIR from Dockerfile
      - gems:/gems # Cache gems from 'bundler' commands (install, update, etc...) in gems volume
      # Keep command history for Bash, IRB and Pry
      - ./docker-files/home/.bash_history:/home/web_app_user/.bash_history
      - ./docker-files/home/.irb_history:/home/web_app_user/.irb_history
      - ./docker-files/home/.pry_history:/home/web_app_user/.pry_history
      - ./docker-files/home/.irbrc:/home/web_app_user/.irbrc # Configure IRB

  # Other services depend on this. It shouldn't be run by itself
  redis:
    # https://hub.docker.com/_/redis
    image: redis:6.2.6
    ports:
      - '6379:6379' # Do not forget to change REDIS_URL when changing this

volumes:
  # Cache gems from 'bundler' commands (install, update, etc...)
  gems:
